security: Low
login success
Traceback (most recent call last):
  File "/data/users/meifukun/liangminhe/Web-vulneble_git/dvwa.py", line 1206, in <module>
    visited_links = get_all_links("http://127.0.0.1:2222/index.php")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/liangminhe/Web-vulneble_git/dvwa.py", line 53, in get_all_links
    link_urls = [link.get_attribute('href') for link in links if link.get_attribute('href')]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/liangminhe/Web-vulneble_git/dvwa.py", line 53, in <listcomp>
    link_urls = [link.get_attribute('href') for link in links if link.get_attribute('href')]
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 233, in get_attribute
    attribute_value = self.parent.execute_script(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 544, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 445, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/meifukun/anaconda3/envs/web-vul-1/lib/python3.11/socket.py", line 718, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
